baseURL: https://pps43.github.io
languageCode: en-us
title: 👨🏼‍🌾
theme: "PaperMod"
copyright: "© 2016-2023 By 波波沙."

googleAnalytics: G-7GDH7EZ6GL
enableInlineShortcodes: true
enableRobotsTXT: true
enableGitInfo: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
hasCJKLanguage: true
ShowPostNavLinks: true
ShowCodeCopyButtons: true
pagination.pagerSize: 20

minify:
    disableXML: true

markup:
    goldmark:
        extensions:
            passthrough:
                enable: true
                delimiters:
                    block:
                        - ['$$', '$$']
                        - ['\[', '\]']
                    inline:
                        - ['$', '$']
                        - ['\(', '\)']

# for search
# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# https://github.com/adityatelange/hugo-PaperMod/wiki/Variables
params:
    env: production
    defaultTheme: auto
    ShowShareButtons: false
    ShareButtons: ["twitter", "zhihu"] # see themes\PaperMod\layouts\partials\share_icons.html

    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false # folder path above title
    ShowCodeCopyButtons: true
    ShowToc: true #show collaspable toc under title
    tocopen: true
    hideSummary: true # summary in card view
    comments: true


    mainSections: ["posts"]

    homeInfoParams:
      Title: "PPS's Garden"
      Content: >
       播撒几粒想法 | 浇灌几株启发 | 除掉几只BUG | 角落开满鲜花
    
    socialIcons:
        - name: Zhihu
          url: "https://www.zhihu.com/people/jiaobai"
        - name: github
          url: "https://github.com/pps43"
        - name: Rss
          url: "index.xml"
    
    assets:
        disableHLJS: false # code highliting

languages:
    en:
      languangeName: "English"
      weight: 1
      taxonomies:
          category: categories
          tag: tags
          series: series
      menu:
          main:
              - name: Archive
                url: archives
                weight: 5
              - name: Search
                url: search/
                weight: 10
              - name: Tags
                url: tags/
                weight: 10
              - name: BookOfGameDev
                url: https://book.enginew.cn/
